services:
  db:
    image: postgres:17
    container_name: crypto_db_container
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}       
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}   
      POSTGRES_DB: ${POSTGRES_DB}        
    ports:
      - "5432:5432"                 # expose port to host
    volumes:
      - postgres_data:/var/lib/postgresql/data

 
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
