"""Update price models

Revision ID: 035a6acc9456
Revises: fe110b2ab271
Create Date: 2025-08-22 17:02:08.155417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '035a6acc9456'
down_revision: Union[str, Sequence[str], None] = 'fe110b2ab271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prices', 'symbol',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('prices', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=8),
               nullable=False)
    op.create_index(op.f('ix_prices_prices_id'), 'prices', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prices_prices_id'), table_name='prices')
    op.alter_column('prices', 'price',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('prices', 'symbol',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
