"""create users table

Revision ID: d57574674e00
Revises: 
Create Date: 2025-08-21 11:33:49.521233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd57574674e00'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_users_id'), 'users', ['id'], unique=False)
    op.drop_table('pgtest')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pgtest',
    sa.Column('testval', sa.VARCHAR(length=10), autoincrement=False, nullable=True)
    )
    op.drop_index(op.f('ix_users_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
