"""create prices table

Revision ID: dcd2d347d648
Revises: d57574674e00
Create Date: 2025-08-21 11:44:57.873177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcd2d347d648'
down_revision: Union[str, Sequence[str], None] = 'd57574674e00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=10), server_default=sa.text("'usd'"), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prices')),
    sa.UniqueConstraint('symbol', 'currency', 'fetched_at', name='uq_prices_symbol_currency_fetched_at')
    )
    op.create_index(op.f('ix_prices_prices_symbol'), 'prices', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prices_prices_symbol'), table_name='prices')
    op.drop_table('prices')
    # ### end Alembic commands ###
